# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_auto_20161215_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='crime_wt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='poi_wt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locality',
            name='traffic_wt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
