# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_auto_20161227_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amusement_park_wt', models.FloatField(default=3.0)),
                ('art_gallery_wt', models.FloatField(default=3.0)),
                ('cafe_wt', models.FloatField(default=3.0)),
                ('casino_wt', models.FloatField(default=3.0)),
                ('hindu_temple_wt', models.FloatField(default=3.0)),
                ('zoo_wt', models.FloatField(default=3.0)),
                ('spa_wt', models.FloatField(default=3.0)),
                ('restaurant_wt', models.FloatField(default=3.0)),
                ('museum_wt', models.FloatField(default=3.0)),
                ('lodging_wt', models.FloatField(default=3.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='locality',
            name='poi_wt',
        ),
        migrations.AlterField(
            model_name='locality',
            name='date',
            field=models.DateField(default=datetime.date(2017, 1, 2)),
        ),
        migrations.AddField(
            model_name='locality',
            name='poi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.PointOfInterests'),
        ),
    ]
